### ISSUE TITLE
Task method not using full variable potential

### ISSUE THREAD

**Issue by autofahrer** [SecondBrainPlanner/SecondBrain#17]
**Beschreibung**
set methods of Task.java only have int variable type but return type is long

**Checkliste**
Bitte bestätige, dass du die folgenden Punkte überprüft hast, bevor du das Issue einreichst:
- [x] Ich habe die neueste Version der App verwendet
- [x] Ich habe nach ähnlichen Issues gesucht und keine doppelten Issues gefunden
- [ ] Ich habe die Schritte zum Reproduzieren des Problems beschrieben

**Comment by Administrator25** [comment]
Ok, in work.

**Comment by Administrator25** [comment]
Lokaler Test ist ohne Problem durchgelaufen
